import { COLORS } from './colors.js';

// install = scrap to mount the weapon in an empty slot. cost/costGrowth = per-level upgrade.
export const WEAPONS = {
  pulse: {
    name: 'Pulse cannon', install: 0,
    desc: 'Fast bolts at the nearest ship. Grows extra barrels at Lv 10/20/30, bolts pierce from Lv 15 and ricochet on kills.',
    dmg: 5, rate: 6, range: 380, speed: 820,
    barrelsAt: [10, 20, 30], pierceAt: [15, 30], ricochetRange: 220, ricochetDmg: 0.7,
    dmgMul: 1.15, rateMul: 1.04,
    cost: 22, costGrowth: 1.4,
    prefer: ['drone', 'swarm'], bonus: 1.4,
    color: COLORS.cyan,
  },
  railgun: {
    name: 'Railgun', install: 250,
    desc: 'Slow, huge hit. Pierces everything in a line. Targets toughest.',
    dmg: 70, rate: 0.6, range: 520,
    dmgMul: 1.18, rateMul: 1.03,
    cost: 90, costGrowth: 1.42,
    prefer: ['shielder', 'boss'], bonus: 1.6, crit: 0.12, critMul: 3,
    color: COLORS.white,
  },
  missile: {
    name: 'Missile pod', install: 400,
    desc: 'Homing missiles with splash. Targets the densest cluster.',
    dmg: 22, rate: 1.4, range: 460, speed: 330, turn: 5, splash: 80,
    dmgMul: 1.16, rateMul: 1.04,
    cost: 105, costGrowth: 1.42,
    prefer: ['raider', 'orbiter'], bonus: 1.5,
    color: COLORS.orange,
  },
  laser: {
    name: 'Laser beam', install: 700,
    desc: 'Continuous beam that ramps on one target and keeps most of its ramp when it switches. From half ramp it forks to nearby ships (more forks at Lv 8, 16, 24); at full ramp it sweeps the whole ring. From Lv 5 its crit ticks burst in an area.',
    dmg: 20, rate: 1, range: 560, rampTime: 3, rampMax: 3, keepRamp: 0.6,
    forksAt: [1, 8, 16, 24], forkDmg: 0.5, forkRamp: 0.5, burstAt: 5, burstRadius: 80,
    sweepEvery: 6, sweepDur: 0.6, sweepMul: 2.5,
    dmgMul: 1.16, rateMul: 1.0,
    cost: 135, costGrowth: 1.42,
    prefer: ['orbiter', 'boss'], bonus: 1.5, crit: 0.08,
    color: COLORS.magenta,
  },
  tesla: {
    name: 'Tesla arc', install: 500,
    desc: 'Chain lightning that jumps between nearby ships.',
    dmg: 14, rate: 1.6, range: 520, chains: 4, chainRange: 220,
    dmgMul: 1.15, rateMul: 1.04,
    cost: 105, costGrowth: 1.42,
    prefer: ['swarm', 'drone'], bonus: 1.6, crit: 0.09,
    color: COLORS.ice,
  },
  gravity: {
    name: 'Gravity well', install: 900,
    desc: 'Launches a singularity that drags ships in and slows them.',
    dmg: 6, rate: 0.3, range: 420, speed: 260, wellRadius: 160, wellLife: 4, pull: 90, slow: 0.45,
    dmgMul: 1.15, rateMul: 1.05,
    cost: 165, costGrowth: 1.42,
    prefer: ['swarm', 'raider'], bonus: 1.4,
    color: COLORS.violet,
  },
  shock: {
    name: 'Shock emitter', install: 600,
    desc: 'Pulses a shockwave that shoves every ship back and clears their shots. Longer push and shorter cooldown per level.',
    dmg: 14, rate: 0.25, range: 320, push: 130, pushPerLevel: 12,
    dmgMul: 1.15, rateMul: 1.05,
    cost: 120, costGrowth: 1.42,
    prefer: ['swarm', 'drone', 'bomber'], bonus: 1.4,
    color: COLORS.green,
  },
  chrono: {
    name: 'Chrono field', install: 900,
    desc: 'Support field. A bubble where time runs slow: ships and their shots inside crawl, your bullets hit harder the longer they spend inside. Barely any damage of its own. From Lv 10 it rewinds every ship inside to where it was 3 s earlier.',
    dmg: 2, rate: 1, range: 260, rangePerLevel: 5, ratio: 0.65, ratioPerLevel: 0.01, ratioMin: 0.35,
    boostPerSec: 0.5, boostMax: 2, rewindAt: 10, rewindEvery: 20, rewindBack: 3,
    dmgMul: 1.10, rateMul: 1.0,
    cost: 150, costGrowth: 1.42,
    prefer: ['raider', 'sniper', 'bomber'], bonus: 1.3,
    color: COLORS.ice,
  },
  nanite: {
    name: 'Replicator swarm', install: 750,
    desc: 'Nanite bolts infect a ship. Hosts take damage over time and when they die the nanites jump to the nearest ships, stronger each generation (more jumps at Lv 8 and 16). From Lv 12 a dying host bursts. Weak alone against a boss, deadly in a pack.',
    dmg: 12, rate: 0.8, range: 480, speed: 520, dur: 8, genMul: 1.35, jumpRange: 240, packRadius: 120,
    jumpsAt: [8, 16], outbreakAt: 12,
    dmgMul: 1.15, rateMul: 1.03,
    cost: 135, costGrowth: 1.42,
    prefer: ['swarm', 'hydra', 'carrier', 'drone'], bonus: 1.4,
    color: COLORS.green,
  },
  singularity: {
    name: 'Singularity core', install: 1200,
    desc: 'Charges from the scrap your kills bring in, then detonates once: every ship in range loses a share of its max HP (bosses capped) and every enemy shot is erased. From Lv 8 the blast leaves a 5 s afterglow where all your hits crit. Feed it with killing weapons.',
    dmg: 0.18, pctMax: 0.55, bossPct: 0.06, rate: 1, range: 400, need: 900, trickle: 10, afterglowAt: 8, afterglowDur: 4,
    // `need` is in threat-1 scrap: it grows with SPAWN.scrapGrowth per threat level, and with the flat scrap multipliers, so a charge stays a fixed number of kills
    support: true,   // cannot be the starting weapon: it only charges from kills made by other slots
    dmgMul: 1.05, rateMul: 1.06,
    cost: 180, costGrowth: 1.44,
    prefer: ['behemoth', 'carrier', 'shielder'], bonus: 1,
    color: COLORS.magenta,
  },
  drones: {
    name: 'Drone bay', install: 600,
    desc: 'Interceptor drones that hunt ships your guns cannot reach first, then work inward. They soak enemy fire and rebuild when lost.',
    dmg: 8, rate: 3.2, range: 640, speed: 850, fireRange: 190,
    drones: 3, dronePerLevels: 3, maxDrones: 8, droneHp: 100, droneHpMul: 1.15, droneSpeed: 260, respawn: 5,
    dmgMul: 1.12, rateMul: 1.03,
    cost: 120, costGrowth: 1.4,
    prefer: ['raider', 'phantom', 'orbiter', 'sniper', 'beacon'], bonus: 1.5,
    color: COLORS.sky,
  },
};
