import { COLORS } from './colors.js';

// install = scrap to mount the weapon in an empty slot. cost/costGrowth = per-level upgrade.
export const WEAPONS = {
  pulse: {
    name: 'Pulse cannon', install: 0,
    desc: 'Fast bolts at the nearest ship. Grows extra barrels at Lv 10/20/30, bolts pierce from Lv 15 and ricochet on kills.',
    dmg: 5, rate: 6, range: 380, speed: 820,
    barrelsAt: [10, 20, 30], pierceAt: [15, 30], ricochetRange: 220, ricochetDmg: 0.7,
    dmgMul: 1.15, rateMul: 1.04,
    cost: 15, costGrowth: 1.3,
    prefer: ['drone', 'swarm'], bonus: 1.4,
    color: COLORS.cyan,
  },
  railgun: {
    name: 'Railgun', install: 250,
    desc: 'Slow, huge hit. Pierces everything in a line. Targets toughest.',
    dmg: 70, rate: 0.6, range: 520,
    dmgMul: 1.18, rateMul: 1.03,
    cost: 60, costGrowth: 1.32,
    prefer: ['shielder', 'boss'], bonus: 1.6, crit: 0.12, critMul: 3,
    color: COLORS.white,
  },
  missile: {
    name: 'Missile pod', install: 400,
    desc: 'Homing missiles with splash. Targets the densest cluster.',
    dmg: 22, rate: 1.4, range: 460, speed: 330, turn: 5, splash: 80,
    dmgMul: 1.16, rateMul: 1.04,
    cost: 70, costGrowth: 1.32,
    prefer: ['raider', 'orbiter'], bonus: 1.5,
    color: COLORS.orange,
  },
  laser: {
    name: 'Laser beam', install: 700,
    desc: 'Continuous beam that ramps on one target. At full ramp it forks to two more ships and periodically sweeps the whole ring.',
    dmg: 20, rate: 1, range: 560, rampTime: 3, rampMax: 3,
    forks: 2, forkDmg: 0.35, sweepEvery: 6, sweepDur: 0.6, sweepMul: 2.5,
    dmgMul: 1.16, rateMul: 1.0,
    cost: 90, costGrowth: 1.32,
    prefer: ['orbiter', 'boss'], bonus: 1.5, crit: 0.08,
    color: COLORS.magenta,
  },
  tesla: {
    name: 'Tesla arc', install: 500,
    desc: 'Chain lightning that jumps between nearby ships.',
    dmg: 14, rate: 1.6, range: 520, chains: 4, chainRange: 220,
    dmgMul: 1.15, rateMul: 1.04,
    cost: 70, costGrowth: 1.32,
    prefer: ['swarm', 'drone'], bonus: 1.6, crit: 0.09,
    color: COLORS.ice,
  },
  gravity: {
    name: 'Gravity well', install: 900,
    desc: 'Launches a singularity that drags ships in and slows them.',
    dmg: 6, rate: 0.3, range: 420, speed: 260, wellRadius: 160, wellLife: 4, pull: 90, slow: 0.45,
    dmgMul: 1.15, rateMul: 1.05,
    cost: 110, costGrowth: 1.32,
    prefer: ['swarm', 'raider'], bonus: 1.4,
    color: COLORS.violet,
  },
  shock: {
    name: 'Shock emitter', install: 600,
    desc: 'Pulses a shockwave that shoves every ship back and clears their shots. Longer push and shorter cooldown per level.',
    dmg: 14, rate: 0.25, range: 320, push: 130, pushPerLevel: 12,
    dmgMul: 1.15, rateMul: 1.05,
    cost: 80, costGrowth: 1.32,
    prefer: ['swarm', 'drone', 'bomber'], bonus: 1.4,
    color: COLORS.green,
  },
  drones: {
    name: 'Drone bay', install: 600,
    desc: 'Interceptor drones that hunt ships your guns cannot reach first, then work inward. They soak enemy fire and rebuild when lost.',
    dmg: 8, rate: 3.2, range: 640, speed: 850, fireRange: 190,
    drones: 3, dronePerLevels: 3, maxDrones: 8, droneHp: 100, droneHpMul: 1.15, droneSpeed: 260, respawn: 5,
    dmgMul: 1.12, rateMul: 1.03,
    cost: 80, costGrowth: 1.3,
    prefer: ['raider', 'phantom', 'orbiter', 'sniper', 'beacon'], bonus: 1.5,
    color: COLORS.sky,
  },
};
